Generic typenames output "fix"
neverlosecc/source2gen pull request #12
Opened 2023-09-04 06:51 UTC by NotOfficer

Im writing a parser this change makes life easier for it.
Example:
`CUtlVector< CStrongHandle< InfoForResourceTypeCTextureBase > >`
changes to
`CUtlVector<CStrongHandle<InfoForResourceTypeCTextureBase>>`

2023-09-04 06:54 UTC, es3n1n requested changes

2023-09-04 06:54 UTC, es3n1n commented on include/tools/codegen.h
> +        static void replace_all(std::string& text, const std::string& to_remove, const std::string& to_insert) {
Not sure if we want to keep this function in the codegen class.

2023-09-04 06:54 UTC, es3n1n commented on include/tools/codegen.h
> +            replace_all(type_name_fixed, "< ", "<");
Please don't hardcode it, add a map of replace-rules at least 😅

2023-09-04 07:13 UTC, NotOfficer commented on include/tools/codegen.h
> +        static void replace_all(std::string& text, const std::string& to_remove, const std::string& to_insert) {
understandable :)

2023-09-04 07:14 UTC, NotOfficer commented on include/tools/codegen.h
> +            replace_all(type_name_fixed, "< ", "<");
i hope my solution is fine for u

2023-09-04 09:24 UTC, es3n1n commented
Ok i thought about it a bit more and the only question that i have is that is there any other types that would have spaces in their names? Can't we just remove all the spaces?

2023-09-04 18:58 UTC, NotOfficer commented
For example `[[maybe_unused]] uint8_t __pad0000[0x8]; // 0x0` will be affected if we remove all spaces -> `[[maybe_unused]]uint8_t ...`

2023-09-04 19:19 UTC, es3n1n commented
> For example `[[maybe_unused]] uint8_t __pad0000[0x8]; // 0x0` will be affected if we remove all spaces -> `[[maybe_unused]]uint8_t ...`

what? no. there's no `[[maybe_unused]]` in their schema, we add it by ourselves huh

2023-09-07 23:03 UTC, NotOfficer commented
well i just mentioned it will get affected aswell. the `[[maybe_unused]] ` part is already added when the function where i added the replacing gets called

2023-09-08 06:53 UTC, es3n1n commented
> well i just mentioned it will get affected aswell. the `[[maybe_unused]] ` part is already added when the function where i added the replacing gets called

What stops you from replacing the spaces **before** adding the maybe_unused attribute?

2023-09-08 08:11 UTC, NotOfficer commented
thats the first function i found to do the replacing in, the code wasnt easy to understand and i do t know for certain if its "safe" to just replace spaces for all types

2023-09-08 08:15 UTC, es3n1n commented
I'll leave this PR open for a while. I'll get back to it whenever I have time (no ETA, sorry)

2024-09-10 20:46 UTC, closed without merging