:circus_tent:
neverlosecc/source2gen pull request #21
Opened 2023-11-06 06:24 UTC by cpz

1. Add Schema stats at end of dumping SDK
2. Netvars now have more static metadata described (e.g. MNetworkEncodeFlags, MNetworkEncoder)
3. Classes now does have static metadata describe
4. Classes now does have flags describe (e.g. Is polymorphic, is abstract and etc)
5. Enum now does have static metadata describe
6. Update SchemaClassInfoData_t
7. Update SchemaClassFlags_t
8. Update SchemaEnumeratorInfoData_t
9. Add some minor functions to SchemaSystem

Reverse Engineering Circus arrived with some ready to cook paste :clown:

2023-11-06 06:26 UTC, cpz commented
![image](https://github.com/neverlosecc/source2gen/assets/31280958/9eb6e7d0-62e7-4007-ae2c-870cf8aae381)
![image](https://github.com/neverlosecc/source2gen/assets/31280958/86b1be41-df43-4e3f-9294-0c8b587b64a3)


Some previews of new metadata in enums\classes

2023-11-06 06:44 UTC, cpz commented
Sometimes it gives us 255 in aligment, so I decided to force 4 if its std::uint8_t::max, idc if its wrong

2023-11-06 06:46 UTC, es3n1n requested changes
Loved it

2023-11-06 06:46 UTC, es3n1n commented on include/sdk/interfaces/schemasystem/schema.h
> +constexpr auto gay = sizeof(bool);
uhm?

2023-11-06 06:46 UTC, es3n1n commented on include/sdk/interfaces/schemasystem/schema.h
> +    {
so what our coding style is after all? thought we were formatting braces like
```cpp
int main() {
    // like this
}
```

2023-11-06 06:46 UTC, es3n1n commented on src/sdk/sdk.cpp
> +        FNV32("MPropertySuppressExpr"),   FNV32("MKV3TransferName"),      FNV32("MFieldVerificationName"),
since we keep adding some entries to these arrays, maybe we should consider moving them to some other file in order to not bloat this file even more than its already

2023-11-06 06:46 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                builder.comment("Is Polymorphic");
Instead of writing some abstract info that nobody would understand, just write exactly what it means
```suggestion
                builder.comment("Has vtable");
```

2023-11-06 06:46 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                builder.comment("Is Abstract");
```suggestion
                builder.comment("Abstract");
```

2023-11-06 06:46 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                if (std::find(kVarNameStringClassMetadataEntries.begin(), kVarNameStringClassMetadataEntries.end(), value_hash_name) != kVarNameStringClassMetadataEntries.end())
not really a fan of this idea anymore, perhaps we could consider creating a general purpose deserialiser for all these vars, and it would stringily its content automatically?

2023-11-06 06:46 UTC, es3n1n commented on src/startup/startup.cpp
> +        static const auto pretiffy_num_fn = reinterpret_cast<const char*(*)(int)>(GetProcAddress(GetModuleHandleA("tier0.dll"), "V_PrettifyNum"));
Please consider moving this function to some wrapper that would be a part of the util namespace or something like that

2023-11-06 06:52 UTC, cpz commented on src/sdk/sdk.cpp
> +                if (std::find(kVarNameStringClassMetadataEntries.begin(), kVarNameStringClassMetadataEntries.end(), value_hash_name) != kVarNameStringClassMetadataEntries.end())
We can, but im not good at this things 💅

2023-11-06 06:53 UTC, cpz commented on include/sdk/interfaces/schemasystem/schema.h
> +    {
Yea, but my vs is sayin fck no, so such shit happens. Ill fix it

2023-11-06 06:54 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                if (std::find(kVarNameStringClassMetadataEntries.begin(), kVarNameStringClassMetadataEntries.end(), value_hash_name) != kVarNameStringClassMetadataEntries.end())
I can do it by myself, if you want. Just let me know

2023-11-06 06:54 UTC, cpz commented on include/sdk/interfaces/schemasystem/schema.h
> +constexpr auto gay = sizeof(bool);
https://youtu.be/7yNwmvNI0k8?si=NjXu-QGZGf0vpnVA

2023-11-06 07:00 UTC, cpz commented on src/sdk/sdk.cpp
> +                if (std::find(kVarNameStringClassMetadataEntries.begin(), kVarNameStringClassMetadataEntries.end(), value_hash_name) != kVarNameStringClassMetadataEntries.end())
If you can then ill apperciate it, cos im going to sleep gn 🫡 ill do changes when will wake up

https://youtu.be/gbt61vcAkG0?si=dVWttKJEHqojjAZT

2023-11-06 07:03 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                if (std::find(kVarNameStringClassMetadataEntries.begin(), kVarNameStringClassMetadataEntries.end(), value_hash_name) != kVarNameStringClassMetadataEntries.end())
Sure, I will take a look at it in my spare time

2023-11-06 15:50 UTC, cpz commented on src/startup/startup.cpp
> +        static const auto pretiffy_num_fn = reinterpret_cast<const char*(*)(int)>(GetProcAddress(GetModuleHandleA("tier0.dll"), "V_PrettifyNum"));
+

2023-11-06 15:50 UTC, cpz commented on src/sdk/sdk.cpp
> +                builder.comment("Is Abstract");
Is Polymorphic\Is Abstract its how valve describes these flags, I agree that 'Is Polymorphic' flag nobody will understand but 'Is Abstract' is not so hard to understand and I think we should keep it as it is

2023-11-06 15:50 UTC, cpz commented on src/sdk/sdk.cpp
> +                builder.comment("Is Polymorphic");
+

2023-11-06 15:50 UTC, cpz commented on src/sdk/sdk.cpp
> +        FNV32("MPropertySuppressExpr"),   FNV32("MKV3TransferName"),      FNV32("MFieldVerificationName"),
I guess you'll do it when gonna write serializer for these things.

2023-11-06 23:17 UTC, cpz commented
![image](https://github.com/neverlosecc/source2gen/assets/31280958/7a7da24d-8788-4b32-a624-c2c98e47cc5f)

todo for future, if there class with pad 0x8 and has flag 'SCHEMA_CF1_HAS_VIRTUAL_MEMBERS' then probably we can make smth like:
```cpp
// Registered binary: client.dll (project 'client')
// Alignment: 8
// Size: 0x78
// Has VTable
// Has Trivial Destructor
// 
// MNetworkVarNames Vector localSound
// MNetworkVarNames int32 soundscapeIndex
// MNetworkVarNames uint8 localBits
// MNetworkVarNames int soundscapeEntityListIndex
// MNetworkVarNames uint32 soundEventHash
struct audioparams_t
{
public: 
        virtual void Destroy() = 0;

public:
	// MNetworkEnable
	// MNetworkEncoder "coord"
	Vector localSound[8]; // 0x8	
	// MNetworkEnable
	int32_t soundscapeIndex; // 0x68	
	// MNetworkEnable
	uint8_t localBits; // 0x6c	
private:
	[[maybe_unused]] uint8_t __pad006d[0x3]; // 0x6d
public:
	// MNetworkEnable
	int32_t soundscapeEntityListIndex; // 0x70	
	// MNetworkEnable
	uint32_t soundEventHash; // 0x74	
};
```

or whatever

2023-11-07 06:13 UTC, es3n1n requested changes
Other than that, looks good

2023-11-07 06:13 UTC, es3n1n commented on include/sdk/interfaces/schemasystem/schema.h
> +    //char pad_0x0010[0x10]; // 0x0010
Do we need this commented out pad? I don't think so

2023-11-09 00:19 UTC, cpz commented
Add acknowledgement (but basically, praydog reverse was used as reference, idk its should be added to acknowledgement).

[Based on this comment](https://github.com/neverlosecc/source2gen/issues/19#issuecomment-1793129027)

2023-11-09 07:50 UTC, es3n1n commented on include/sdk/interfaces/schemasystem/schema.h
> + * Source2Gen
Did you just put the license info only to one file? Why?

2023-11-09 15:11 UTC, es3n1n approved these changes
meeergeeeeed 🎉

2023-11-09 15:12 UTC, merged