Embedding non-pointer props
neverlosecc/source2gen pull request #28
Opened 2024-01-13 04:11 UTC by DucaRii

I went ahead and implemented my idea from https://github.com/neverlosecc/source2gen/issues/26

Ive opted to go with adding the offsets into the metadata of the prop for simplicity sake. Though i still had to make minor changes to the code structure in order to avoid bloat.

The conditions for whether a prop should be directly embedded are as follows
- Does it have more than 1 field and less than 13 fields (random numbers i just pulled out of my ass)
- Is it not used by more than 2 classes (some classes such as GameTime_t are used all over the place and in order to avoid bloating the dump with a bunch of embedded data i decided it'd be a good idea to only embed classes that arent frequently used)

With the changes applied a dump will now embed ~50 classes across all binaries and will look like this
```c++
// MNetworkEnable
// -> m_hModel - 0x200
// -> m_ModelName - 0x208
// -> m_bClientClothCreationSuppressed - 0x248
// -> m_MeshGroupMask - 0x2e0
// -> m_nIdealMotionType - 0x382
// -> m_nForceLOD - 0x383
// -> m_nClothUpdateFlags - 0x384
CModelState m_modelState; // 0x160	
```

2024-01-14 06:08 UTC, es3n1n requested changes
Other than that, lgtm, thank you. 
Although I didn't test it in game yet, but I don't see any reasons why it shouldn't work.

2024-01-14 06:08 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                    if ( field_class != classes_to_dump.end() )
```suggestion
                    if (field_class != classes_to_dump.end())
```

2024-01-14 06:08 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                    if ( prop_class != classes_to_dump.end() )
```suggestion
                    if (prop_class != classes_to_dump.end())
```

2024-01-14 06:08 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                        if (prop_class->cached_fields_.size() < 2 || prop_class->cached_fields_.size() > 12)
Probably these magic numbers should be moved to some constexpr variables.

2024-01-14 06:08 UTC, es3n1n commented on src/sdk/sdk.cpp
> +                        if (prop_class->used_count_ > 2)
This one should be moved to a constexpr var too.

2024-01-14 06:08 UTC, es3n1n commented on include/tools/codegen.h
> -
this one should stay

2024-01-15 18:15 UTC, DucaRii commented
alright should be good 2 go, couldnt really think of a good name for the "used_by_" constant but this one should be good enough

2024-01-15 18:15 UTC, es3n1n approved these changes

2024-01-18 21:55 UTC, es3n1n commented
@cpz is a bit busy with some other stuff for now, as soon as he reviews this PR, we will merge it. sorry for the delays :)

2024-01-18 23:39 UTC, DucaRii commented
all good ^.^

2024-01-23 16:31 UTC, cpz commented
👍

2024-01-23 16:32 UTC, merged