feat: add cmake support
neverlosecc/source2gen pull request #37
Opened 2024-03-02 13:13 UTC by kehrazy

This pull request adds basic CMake support.

2024-03-02 13:16 UTC, kehrazy commented
this does require further tweaking tho, but it builds with msvc :)

2024-03-02 15:16 UTC, es3n1n requested changes
Looks good, just a few minor changes.

As a side note, do we **really** need to support both premake5 and cmake after we merge this? Perhaps it's finally time to get rid of premake5? @cpz

2024-03-02 15:16 UTC, es3n1n commented on CMakeLists.txt
> +if(CMAKE_SIZEOF_VOID_P EQUAL 4)
Not too sure about this one, as per [docs](https://cmake.org/cmake/help/latest/variable/CMAKE_SIZEOF_VOID_P.html) it returns the size of a pointer on **the target machine**, not the target.
If we really want to check the architecture, a better solution would probably be to check it in the C++ code instead.

2024-03-02 15:16 UTC, es3n1n commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require C++ standard")
Do we really need this? Aren't we setting this manually and there shouldn't be any cases where it could be unset?

2024-03-02 15:16 UTC, es3n1n commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
This should be set by the user manually, if they want to generate compile commands.

2024-03-02 15:16 UTC, es3n1n commented on CMakeLists.txt
> +    message(FATAL_ERROR "In-source builds not allowed. Please make a new directory (called a build directory) and run CMake from there. You may need to remove CMakeCache.txt. ")
```suggestion
    message(FATAL_ERROR "In-source builds are not allowed. Please make a new directory (called a build directory) and run CMake from there. You may need to remove CMakeCache.txt. ")
```

2024-03-02 15:16 UTC, es3n1n commented on CMakeLists.txt
> +
```suggestion
```

2024-03-02 15:40 UTC, kehrazy commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require C++ standard")
> Do we really need this? Aren't we setting this manually and there shouldn't be any cases where it could be unset?

I was porting the premake5 config. In there we had the "latest" C++ - so we have a C++ standard option. This is probably useless in the grand scheme of things, and no, we really don't need this. We can, however, check for C++23 support with `check_cxx_compiler_flag` down the aisle, and move on from there.

2024-03-02 15:41 UTC, kehrazy commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
Sure.

2024-03-02 15:44 UTC, kehrazy commented on CMakeLists.txt
> +if(CMAKE_SIZEOF_VOID_P EQUAL 4)
Eh. Yeah.

We can use `check_cxx_source_compiles` with `static_assert` to determine the target pointer width.

2024-03-02 15:54 UTC, kehrazy commented on CMakeLists.txt
> +if(CMAKE_SIZEOF_VOID_P EQUAL 4)
Nah, we're wrong, and cmake is right. As per usual.

![this thing](https://github.com/neverlosecc/source2gen/assets/100174039/8d8f470a-c184-4bd5-acad-d5774bd38609)

this thing doesn't work on x86 __targets__. So this should be a valid check.

2024-03-03 23:02 UTC, es3n1n approved these changes

2024-03-03 23:02 UTC, merged

2024-03-03 23:02 UTC, es3n1n commented
Thanks!