WIP: :circus_tent: (DEADLOCK)
neverlosecc/source2gen pull request #51
Opened 2024-05-26 19:25 UTC by cpz

Initial deadlock game supporting.

2024-05-31 05:53 UTC, es3n1n requested changes
other than that lgtm

2024-05-31 05:53 UTC, es3n1n commented on premake5.lua
> +    filter { "options:game=DEADLOCK" }
where's cmakelists update? this is exactly the reason why we should drop this stupid premake5 thingy.

2024-05-31 17:54 UTC, cpz commented on premake5.lua
> +    filter { "options:game=DEADLOCK" }
不要讓我知道那個名為 cmake 的東西，不要這樣談論我喜歡的 premake

2024-08-25 20:22 UTC, es3n1n approved these changes

2024-08-25 20:24 UTC, merged